version: '3.4'

services:
  app: 
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - GRADLE_OPTS
    environment:
      - GRADLE_OPTS
      - http_proxy
      - https_proxy
    command: npm start
    volumes:
      - .:/srv
