  
version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
            docker-compose -v
            docker-compose config
      - run:
          name: Build Demo
          command: |
            docker-compose build
            docker-compose run --rm app yarn install
            docker-compose up -d app
            
      - run:
          name: Tpye check App
          command: |
            docker-compose exec app yarn ex build

      - run:
          name: Build Demo App
          command: |
            docker-compose exec app yarn ex gradle assembleRelease




workflows:
  main:
    jobs:
      - build
